# 1. Base image and global setup
FROM node:22.8.0 AS base
WORKDIR /usr/src/app
RUN npm install -g yarn

# 2. Dependencies installation
FROM base AS dependencies
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile

# 3. Build stage
FROM dependencies AS build
COPY . .
RUN node --max-old-space-size=4096 $(yarn bin)/vite build  # Increase memory allocation

# 4. Production image
FROM nginx:alpine AS production
COPY --from=build /usr/src/app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
