# 1. Base image and global setup
FROM node:22.8.0 AS base
WORKDIR /usr/src/app
RUN npm install -g npm@8

# 2. Dependencies installation
FROM base AS dependencies
COPY package*.json ./
RUN npm ci

# 3. Build stage
FROM dependencies AS build
COPY . .
RUN npm run build

# 4. Production image
FROM nginx:alpine AS production
COPY --from=build /usr/src/app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
