version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - ATLAS_URI=${ATLAS_URI}   # MongoDB URI as an environment variable
    depends_on:
      - mongo
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80" # 80 is the default port for Nginx, mapped to 3000
    depends_on:
      - backend
    networks:
      - mern-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern-network
    environment:
      MONGO_INITDB_DATABASE: mydatabase

networks:
  mern-network:
    driver: bridge
