# Use an official Node.js runtime as a parent image
FROM node:22.8.0

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the backend port (e.g., 5000)
EXPOSE 5000

# Define the command to run your app
CMD ["npm", "start"]