name: MERN CI/CD Pipeline with Docker

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0' 

      # Install Yarn globally
      - name: Install Yarn
        run: |
          npm install -g yarn

      # Backend-specific steps
      # Step 3: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          yarn install --frozen-lockfile

      # Step 4: Run backend tests
      - name: Run backend tests
        run: |
          cd backend
          yarn test

      # Frontend-specific steps
      # Step 5: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          yarn install --frozen-lockfile

      # Step 6: Build frontend
      - name: Build frontend
        run: |
          cd frontend
          yarn build

      # Step 7: Run frontend tests
      - name: Run frontend tests
        run: |
          cd frontend
          yarn test

      # Step 8: Log in to Docker Hub using the secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 9: Build and push backend Docker image
      - name: Build and push backend image
        run: |
          docker build -t jenshols/mern-backend ./backend
          docker push jenshols/mern-backend

      # Step 10: Build and push frontend Docker image
      - name: Build and push frontend image
        run: |
          docker build -t jenshols/mern-frontend ./frontend
          docker push jenshols/mern-frontend

      # Step 11: Deploy to DigitalOcean
      - name: Deploy to DigitalOcean server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_ACTIONS_KEY }}
          script: |
            echo "Starting deploy process..."
            cd /home/deployer/projects/auction
            echo "Pulled into the project directory"

            export NODE_ENV=${{ secrets.NODE_ENV }}
            export ATLAS_URI=${{ secrets.ATLAS_URI }}
            export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
            export BASE_URL=${{ secrets.BASE_URL }}
            export REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}
            export MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            export MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}

            echo "Environment variables set."
            bash deploy.sh
            echo "Deployment completed successfully"
          command_timeout: 60m
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}  # Node environment variable
          ATLAS_URI: ${{ secrets.ATLAS_URI }}  # Atlas for MongoDB
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}  # MongoDB username
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}  # MongoDB password
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }} # possibly redundant
