name: Basic MERN CI Pipeline

on:
  push:
    branches:
      - main
      - developer
  pull_request:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub using the secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and push backend Docker image
      - name: Build and push backend image
        run: |
          docker build -t jenshols/mern-backend ./backend
          docker push jenshols/mern-backend

      # Step 4: Build and push frontend Docker image
      - name: Build and push frontend image
        run: |
          docker build -t jenshols/mern-frontend ./frontend
          docker push jenshols/mern-frontend

      # Step 5: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0' 

      # Backend-specific steps
      # Step 6: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      # Step 7: Run backend tests
      - name: Run backend tests
        run: |
          cd backend
          npm test

      # Frontend-specific steps
      # Step 8: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      # Step 9: Build frontend
      - name: Build frontend
        run: |
          cd frontend
          npm run build

      # Step 10: Run frontend tests
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

      # Step 11: Deploy to DigitalOcean

      - name: Deploy to DigitalOcean server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.PRIVATE_ACTIONS_KEY }}
       #   script: |
       #     /path/to/your/deploy.sh
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}  # Nodne environment variable
          ATLAS_URI: ${{ secrets.ATLAS_URI }}  # Atlas for MongoDB
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}  # MongoDB username
          MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}  # MongoDB password
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
          PORT: ${{ secrets.PORT }}
          #REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }} # probably redundant